[project]
name = "data-platform-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django==6.0.7",
    "django-azure-auth==2.6.0",
    "django-extensions==4.1",
    "django-simple-history==3.13.0",
    "gunicorn==26.0.0",
    "httpx==0.28.1",
    "model-bakery==1.24.0",
    "python-dotenv==1.2.2",
    "psycopg[binary]==3.3.4",
    "pytest-django==4.12.0",
    "pytest-cov==7.1.0",
    "whitenoise==6.12.0",
    "cryptography==49.0.0",
    "sentry-sdk==2.66.1",
    "django-htmx==1.28.0",
    "notifications-python-client==12.1.0",
]

[dependency-groups]
dev = [
    "djlint==1.43.0",
    "django-debug-toolbar==7.0.0",
    "pre-commit==4.6.1",
    "pytest==9.1.1",
    "ruff==0.16.1",
]

[tool.ruff]
line-length = 99

[tool.uv]
exclude-newer = "7d"

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]

[tool.ruff.lint.per-file-ignores]
"**/migrations/*.py" = ["E501"]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "data_platform_app.settings.test"
addopts = "-v --tb=auto --cov=data_platform_app --cov=users --cov=projects --cov=ai_gateway --cov-branch --cov-report=term-missing --cov-report=xml --cov-fail-under=90"
testpaths = ["tests"]

[tool.coverage.run]
omit = [
    "*/migrations/*",
    "data_platform_app/settings/*",
    "data_platform_app/wsgi.py",
    "data_platform_app/asgi.py",
    "manage.py",
]

[tool.djlint]
profile = "django"
indent = 2
max_line_length = 99
format_css = true
format_js = true
ignore = "H006,H021,H023,H025,H030,H031,T002"
