---
name: Chart Lint

on:
  pull_request:
    branches:
      - main
      - development

permissions: {}

jobs:
  chart-lint:
    name: Chart Lint
    permissions:
      contents: read
    uses: ministryofjustice/data-platform-github-actions/.github/workflows/chart-lint.yml@82df95393d34df015c468f09e44890271448de16 # v4.0.12
