---
name: Container Scan

on:
  pull_request:
    branches:
      - main
      - development

permissions: {}

jobs:
  container-scan:
    name: Container Scan
    permissions:
      contents: read
      pull-requests: write
      security-events: write
    uses: ministryofjustice/data-platform-github-actions/.github/workflows/container-scan.yml@82df95393d34df015c468f09e44890271448de16 # v4.0.12
    with:
      containerfile-path: Dockerfile
