---
name: Container Release

on:
  push:
    tags:
      - "*"

permissions: {}

jobs:
  container-release:
    name: Container Release
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write
    uses: ministryofjustice/data-platform-github-actions/.github/workflows/container-release.yml@82df95393d34df015c468f09e44890271448de16 # v4.0.12
    with:
      containerfile-path: Dockerfile
