---
name: Spell Check

on:
  pull_request:
    branches:
      - main
      - development

permissions: {}

jobs:
  spell-check:
    name: Spell Check
    permissions:
      contents: read
    uses: ministryofjustice/data-platform-github-actions/.github/workflows/spell-check.yml@82df95393d34df015c468f09e44890271448de16 # v4.0.12
