---
name: Super Linter

on:
  pull_request:
    branches:
      - main
      - development

permissions: {}

jobs:
  super-linter:
    name: Super Linter
    permissions:
      contents: read
      packages: read
      statuses: write
    uses: ministryofjustice/data-platform-github-actions/.github/workflows/super-linter.yml@82df95393d34df015c468f09e44890271448de16 # v4.0.12
    with:
      super-linter-variables: |
        {
          "LINTER_RULES_PATH": ".",
          "PYTHON_RUFF_FORMAT_CONFIG_FILE": "pyproject.toml",
          "VALIDATE_CHECKOV": false,
          "VALIDATE_CSS": false,
          "VALIDATE_DOCKERFILE_HADOLINT": false,
          "VALIDATE_HTML": false,
          "VALIDATE_HTML_PRETTIER": false,
          "VALIDATE_JSCPD": false,
          "VALIDATE_JUPYTER_NBQA_RUFF": false,
          "VALIDATE_KUBERNETES_KUBECONFORM": false,
          "VALIDATE_PYTHON_BLACK": false,
          "VALIDATE_PYTHON_FLAKE8": false,
          "VALIDATE_PYTHON_ISORT": false,
          "VALIDATE_PYTHON_PYLINT": false,
          "VALIDATE_PYTHON_MYPY": false
        }
